generated: '2026-07-11'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: www.uipath.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Oct  4 09:49:48 2026 GMT
  hsts: false
- host: cloud.uipath.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Oct  1 11:12:55 2026 GMT
  hsts: null
- host: docs.uipath.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Oct  4 05:16:45 2026 GMT
  hsts: null
domains:
- domain: uipath.com
  dnssec: true
  caa:
  - 0 issue "pki.goog; cansignhttpexchanges=yes"
  - 0 issue "ssl.com"
  - 0 issue "ssladmin.microsoft.com"
  - 0 issue "web.com"
  - 0 issuewild "comodoca.com"
  - 0 issuewild "digicert.com; cansignhttpexchanges=yes"
  spf: true
  dmarc: true
  dmarc_policy: quarantine
